/**
 * Scene Generator Service
 * Takes a script and produces a fully structured TimelineState:
 *  1. Splits script → scenes
 *  2. Generates TTS voiceover per scene
 *  3. Generates subtitle entries
 *  4. Builds VideoScene records in DB
 *  5. Assembles TimelineState JSON
 */

import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { TtsService } from './tts.service';
import { SubtitleService } from './subtitle.service';
import { StorageService } from './storage.service';
import {
  TimelineState,
  VideoTrack,
  AudioTrack,
  TextTrack,
  VideoClip,
  AudioClip,
  TextClip,
  SceneGenerationRequest,
} from '../types/video.types';
import * as crypto from 'crypto';

const WORDS_PER_MINUTE = 150;
const MIN_SCENE_MS     = 3_000;
const PADDING_MS       = 500;   // tail silence per scene

@Injectable()
export class SceneGeneratorService {
  private readonly logger = new Logger(SceneGeneratorService.name);

  constructor(
    private readonly prisma:    PrismaService,
    private readonly tts:       TtsService,
    private readonly subtitles: SubtitleService,
    private readonly storage:   StorageService,
  ) {}

  // ── Main entry point ──────────────────────────────────────────────────────

  async generateFromScript(req: SceneGenerationRequest): Promise<TimelineState> {
    const { projectId, organizationId, script, voiceId = 'nova' } = req;

    this.logger.log(`Generating scenes for project ${projectId}`);

    const segments = this.tts.splitScriptIntoSegments(script);
    if (!segments.length) throw new Error('Script produced no segments');

    const sceneData: Array<{
      text: string;
      durationMs: number;
      voiceoverKey: string | null;
    }> = [];

    // Generate TTS per segment + upload to storage
    for (const text of segments) {
      let durationMs = this.estimateDuration(text);
      let voiceoverKey: string | null = null;

      try {
        const { audioPath, durationMs: ttsDuration } = await this.tts.synthesize(text, {
          voice: voiceId as any,
        });
        durationMs   = ttsDuration + PADDING_MS;
        voiceoverKey = await this.storage.uploadTemp(
          audioPath,
          organizationId,
          `voiceover-${crypto.randomUUID()}.mp3`,
        );
      } catch (err: unknown) {
        this.logger.warn(`TTS failed for segment, using estimated timing: ${(err as Error).message}`);
      }

      sceneData.push({ text, durationMs: Math.max(durationMs, MIN_SCENE_MS), voiceoverKey });
    }

    // Upsert VideoScene rows
    await this.prisma.videoScene.deleteMany({ where: { videoProjectId: projectId } });
    const scenes = await Promise.all(
      sceneData.map((d, i) =>
        this.prisma.videoScene.create({
          data: {
            videoProjectId: projectId,
            order:          i,
            scriptSegment:  d.text,
            durationMs:     d.durationMs,
            voiceoverUrl:   d.voiceoverKey ? this.storage.publicUrl(d.voiceoverKey) : null,
            voiceoverText:  d.text,
            ttsVoiceId:     voiceId,
          },
        }),
      ),
    );

    // Build subtitle track
    const subResult = this.subtitles.generateFromScript(
      sceneData.map((d) => d.text),
      sceneData.map((d) => d.durationMs),
    );

    // Persist subtitle track
    await this.prisma.subtitleTrack.create({
      data: {
        videoProjectId: projectId,
        srtContent:     subResult.srt,
        vttContent:     subResult.vtt,
        autoGenerated:  true,
      },
    });

    // Assemble TimelineState
    const timeline = this.buildTimeline(scenes, sceneData, req);

    // Persist timeline JSON back to project
    await this.prisma.videoProject.update({
      where: { id: projectId },
      data:  {
        timelineJson: JSON.stringify(timeline),
        durationMs:   timeline.durationMs,
      },
    });

    this.logger.log(`Scene generation complete: ${scenes.length} scenes, ${timeline.durationMs}ms`);
    return timeline;
  }

  // ── Timeline builder ──────────────────────────────────────────────────────

  private buildTimeline(
    scenes: Array<{ id: string; durationMs: number; voiceoverUrl: string | null; scriptSegment: string | null }>,
    sceneData: Array<{ text: string; durationMs: number; voiceoverKey: string | null }>,
    req: SceneGenerationRequest,
  ): TimelineState {
    const totalDuration = sceneData.reduce((sum, d) => sum + d.durationMs, 0);

    const [width, height] = this.resolveResolution(req.aspectRatio ?? '16:9');

    // Video track — black clips per scene
    const videoClips: VideoClip[] = [];
    const audioClips: AudioClip[] = [];
    const textClips:  TextClip[]  = [];

    let cursor = 0;
    for (let i = 0; i < scenes.length; i++) {
      const scene   = scenes[i];
      const dur     = sceneData[i].durationMs;
      const startMs = cursor;

      // Video clip baseline (replaced when AI image generation runs)
      videoClips.push({
        kind:         'video',
        id:           `vclip-${scene.id}`,
        assetId:      '', // empty until AI image assigned
        startMs,
        durationMs:   dur,
        trimStartMs:  0,
        trimEndMs:    dur,
        volume:       0,
        speed:        1,
        muted:        true,
        opacity:      100,
        filters:      [],
      });

      // Voiceover audio clip
      if (sceneData[i].voiceoverKey) {
        audioClips.push({
          kind:        'audio',
          id:          `aclip-${scene.id}`,
          assetId:     scene.id,
          startMs,
          durationMs:  dur,
          trimStartMs: 0,
          trimEndMs:   dur,
          volume:      1,
          speed:       1,
          opacity:     100,
        });
      }

      // Subtitle text clip
      if (scene.scriptSegment) {
        textClips.push({
          kind:       'text',
          id:         `tclip-${scene.id}`,
          text:       scene.scriptSegment,
          startMs,
          durationMs: dur,
          opacity:    100,
          fontFamily: 'Inter, sans-serif',
          fontSize:   36,
          fontWeight: 'bold',
          color:      '#FFFFFF',
          background: 'rgba(0,0,0,0.5)',
          align:      'center',
          position:   { x: 0, y: height * 0.8 },
          isSubtitle: true,
        });
      }

      cursor += dur;
    }

    const videoTrack: VideoTrack = {
      kind:   'video',
      id:     'track-video-main',
      name:   'Main Video',
      locked: false,
      muted:  false,
      clips:  videoClips,
    };

    const audioTrack: AudioTrack = {
      kind:   'audio',
      id:     'track-audio-voiceover',
      name:   'Voiceover',
      locked: false,
      muted:  false,
      clips:  audioClips,
    };

    const subtitleTrack: TextTrack = {
      kind:   'text',
      id:     'track-text-subtitles',
      name:   'Subtitles',
      locked: false,
      muted:  false,
      clips:  textClips,
    };

    return {
      version:    1,
      durationMs: totalDuration,
      width,
      height,
      fps:        30,
      tracks:     [videoTrack, audioTrack, subtitleTrack],
    };
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private estimateDuration(text: string): number {
    const words = text.split(/\s+/).length;
    return Math.round((words / WORDS_PER_MINUTE) * 60_000) + PADDING_MS;
  }

  private resolveResolution(ratio: '16:9' | '9:16' | '1:1'): [number, number] {
    if (ratio === '9:16') return [1080, 1920];
    if (ratio === '1:1')  return [1080, 1080];
    return [1920, 1080];
  }
}
