'use client';

import { useState, useCallback, useEffect } from 'react';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface VideoProject {
  id: string;
  title: string;
  description?: string;
  status: 'DRAFT' | 'PROCESSING' | 'READY' | 'FAILED' | 'ARCHIVED';
  outputUrl?: string;
  thumbnailUrl?: string;
  durationMs?: number;
  width: number;
  height: number;
  fps: number;
  createdAt: string;
  updatedAt: string;
  _count?: { scenes: number; processingJobs: number };
}

export interface VideoScene {
  id: string;
  order: number;
  scriptSegment?: string;
  durationMs: number;
  voiceoverUrl?: string;
  backgroundUrl?: string;
}

export interface MediaAsset {
  id: string;
  name: string;
  mediaType: 'VIDEO_CLIP' | 'AUDIO_CLIP' | 'IMAGE' | 'SUBTITLE_TRACK' | 'VOICEOVER' | 'BACKGROUND_MUSIC';
  mimeType: string;
  publicUrl?: string;
  durationMs?: number;
  width?: number;
  height?: number;
  aiGenerated: boolean;
  createdAt: string;
}

export interface RenderJob {
  id: string;
  jobType: string;
  status: 'QUEUED' | 'PROCESSING' | 'DONE' | 'FAILED';
  progress: number;
  errorMessage?: string;
  createdAt: string;
  completedAt?: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  srtContent?: string;
  vttContent?: string;
  autoGenerated: boolean;
}

// ── Auth header helper ────────────────────────────────────────────────────────

function authHeader(): HeadersInit {
  const token = typeof window !== 'undefined' ? localStorage.getItem('accessToken') : null;
  return token ? { Authorization: `Bearer ${token}` } : {};
}

async function apiFetch<T>(url: string, opts?: RequestInit): Promise<T> {
  const res = await fetch(url, {
    ...opts,
    headers: { 'Content-Type': 'application/json', ...authHeader(), ...(opts?.headers ?? {}) },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ message: res.statusText }));
    throw new Error(err.message ?? `HTTP ${res.status}`);
  }
  return res.json();
}

// ── Hook ──────────────────────────────────────────────────────────────────────

export function useVideoProjects() {
  const [projects, setProjects] = useState<VideoProject[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await apiFetch<VideoProject[]>('/api/video/projects');
      setProjects(data);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const createProject = useCallback(async (title: string, aspectRatio = '16:9') => {
    const proj = await apiFetch<VideoProject>('/api/video/projects', {
      method: 'POST',
      body: JSON.stringify({ title, aspectRatio }),
    });
    setProjects((prev) => [proj, ...prev]);
    return proj;
  }, []);

  const deleteProject = useCallback(async (id: string) => {
    await apiFetch(`/api/video/projects/${id}`, { method: 'DELETE' });
    setProjects((prev) => prev.filter((p) => p.id !== id));
  }, []);

  return { projects, loading, error, refresh: load, createProject, deleteProject };
}

export function useVideoEditor(projectId: string) {
  const [project, setProject] = useState<VideoProject & { scenes: VideoScene[]; mediaAssets: MediaAsset[]; processingJobs: RenderJob[]; subtitleTracks: SubtitleTrack[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [rendering, setRendering] = useState(false);

  const load = useCallback(async () => {
    if (!projectId) return;
    setLoading(true);
    try {
      const data = await apiFetch<any>(`/api/video/projects/${projectId}`);
      setProject(data);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }, [projectId]);

  useEffect(() => { load(); }, [load]);

  const generateFromScript = useCallback(async (script: string, voiceId = 'nova', aspectRatio = '16:9') => {
    setGenerating(true);
    try {
      await apiFetch(`/api/video/projects/${projectId}/generate`, {
        method: 'POST',
        body: JSON.stringify({ script, voiceId, aspectRatio }),
      });
      await load();
    } finally {
      setGenerating(false);
    }
  }, [projectId, load]);

  const saveTimeline = useCallback(async (timelineJson: string) => {
    await apiFetch(`/api/video/projects/${projectId}/timeline`, {
      method: 'PUT',
      body: JSON.stringify({ timelineJson }),
    });
  }, [projectId]);

  const queueRender = useCallback(async (format = 'mp4', quality = 'medium') => {
    setRendering(true);
    try {
      const result = await apiFetch<{ jobId: string; bullJobId: string }>(
        `/api/video/projects/${projectId}/render`,
        { method: 'POST', body: JSON.stringify({ format, quality }) },
      );
      await load();
      return result;
    } finally {
      setRendering(false);
    }
  }, [projectId, load]);

  const updateScene = useCallback(async (sceneId: string, patch: Partial<VideoScene>) => {
    await apiFetch(`/api/video/projects/${projectId}/scenes/${sceneId}`, {
      method: 'PATCH',
      body: JSON.stringify(patch),
    });
    await load();
  }, [projectId, load]);

  const uploadMedia = useCallback(async (file: File) => {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('projectId', projectId);
    const res = await fetch('/api/video/media/upload', {
      method: 'POST',
      headers: authHeader(),
      body: formData,
    });
    if (!res.ok) throw new Error('Upload failed');
    await load();
    return res.json();
  }, [projectId, load]);

  const deleteAsset = useCallback(async (assetId: string) => {
    await apiFetch(`/api/video/media/${assetId}`, { method: 'DELETE' });
    await load();
  }, [load]);

  const generateSubtitles = useCallback(async (language = 'en') => {
    await apiFetch(`/api/video/projects/${projectId}/subtitles/generate`, {
      method: 'POST',
      body: JSON.stringify({ language }),
    });
    await load();
  }, [projectId, load]);

  const pollRenderStatus = useCallback(async () => {
    const jobs = await apiFetch<RenderJob[]>(`/api/video/projects/${projectId}/render/status`);
    return jobs;
  }, [projectId]);

  return {
    project,
    loading,
    error,
    generating,
    rendering,
    refresh: load,
    generateFromScript,
    saveTimeline,
    queueRender,
    updateScene,
    uploadMedia,
    deleteAsset,
    generateSubtitles,
    pollRenderStatus,
  };
}
